#   (c) Copyright 2014-2017 Hewlett-Packard Enterprise Development Company, L.P.
#   All rights reserved. This program and the accompanying materials
#   are made available under the terms of the Apache License v2.0 which accompany this distribution.
#
#   The Apache License is available at
#   http://www.apache.org/licenses/LICENSE-2.0
#
########################################################################################################################

language: java

sudo: required

services:
  - docker

env:
 global:
   - JAVA_OPTS="-XX:MaxPermSize=512m"
 matrix:
   - SUITE=containers
   - SUITE=images
   - SUITE=docker-misc,docker_examples
   - SUITE=git,remote-copy

script:
  - chmod +x ci-env/travis/run_containers.sh && ci-env/travis/run_containers.sh
  - docker ps -a
  - docker info
  - docker version
  - df -kh
  - wget https://github.com/CloudSlang/cloud-slang/releases/download/cloudslang-1.0.6/cslang-builder.zip
  - unzip -q cslang-builder.zip
  - chmod +x cslang-builder/bin/cslang-builder
  - ./cslang-builder/bin/cslang-builder -ts ${SUITE},\!default -cov -des -cs

# cat prints only part of the file for some reason so we print ourselves
after_failure: while read line; do printf "%s\n" "$line"; done < ./cslang-builder/logs/builder.log

